apiVersion: v1
kind: Service
metadata:
  name: cnpg-cluster-nodeport
  namespace: cnpg-cluster
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: cnpg-cluster
    role: primary
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432  # Access via localhost:30432
